spring:
  main:
    banner-mode: 'off'
  profiles:
    active: dev
---
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: AtulAnand
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
---
spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: AtulAnand
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system